/**
 * Server-only helpers for finalizing a spanduk after the AI returns
 * the raw image:
 *   1. Resize/crop to exact print dimensions.
 *   2. Wrap the final PNG into a single-page PDF whose page size
 *      matches the spanduk's physical dimensions (1 cm = 28.3464567 pt).
 *
 * Historical note: this module used to also composite a vector text
 * overlay (headline / subhead / phone / address) onto the AI background.
 * We dropped that path when the full-AI flow became the only mode —
 * Gemini renders the text directly inside the image now, so an SVG
 * overlay would only obscure it.
 *
 * This module must not leak into the client bundle. Keep it under
 * `apps/web/src/server/lib/` and never re-export from a route file.
 */

import sharp from 'sharp'
import { PDFDocument } from 'pdf-lib'

// Aspect ratios Gemini supports natively for image generation.
// We pick the closest match to the spanduk's aspect ratio, then
// resize:cover to crop to the exact W×H of the print target.
const GEMINI_RATIOS: Array<{ key: string; ratio: number }> = [
  { key: '21:9', ratio: 21 / 9 },
  { key: '16:9', ratio: 16 / 9 },
  { key: '4:3', ratio: 4 / 3 },
  { key: '1:1', ratio: 1 },
  { key: '3:4', ratio: 3 / 4 },
  { key: '9:16', ratio: 9 / 16 },
]

/** Map physical W×H (cm) to the closest Gemini-supported aspect ratio. */
export function pickGeminiAspectRatio(widthCm: number, heightCm: number): string {
  const target = widthCm / heightCm
  let bestKey = '16:9'
  let bestDelta = Number.POSITIVE_INFINITY
  for (const { key, ratio } of GEMINI_RATIOS) {
    const delta = Math.abs(ratio - target)
    if (delta < bestDelta) {
      bestDelta = delta
      bestKey = key
    }
  }
  return bestKey
}

/**
 * Map physical dimensions to an output pixel size that gives ~150 DPI
 * at print size, with a long-edge cap so we don't blow memory at 8m+
 * banner widths.
 *
 *   150 DPI ≈ 59 px per cm.
 */
const PX_PER_CM = 59
const MAX_LONG_EDGE_PX = 6144

export function pickOutputPixelSize(
  widthCm: number,
  heightCm: number,
): { widthPx: number; heightPx: number } {
  let widthPx = Math.round(widthCm * PX_PER_CM)
  let heightPx = Math.round(heightCm * PX_PER_CM)
  const longest = Math.max(widthPx, heightPx)
  if (longest > MAX_LONG_EDGE_PX) {
    const scale = MAX_LONG_EDGE_PX / longest
    widthPx = Math.round(widthPx * scale)
    heightPx = Math.round(heightPx * scale)
  }
  return { widthPx, heightPx }
}

export interface ComposeSpandukParams {
  /** Raw AI image bytes (PNG/JPEG/WebP). Contains the full spanduk
   *  including text — generated by Gemini in one shot. */
  imageBytes: Buffer
  /** Target print dimensions in centimeters. */
  widthCm: number
  heightCm: number
  /** When true, also build the print-ready PDF. Preview generations
   *  skip this (PNG-only) to save time and storage. */
  buildPdf?: boolean
}

export interface ComposeSpandukResult {
  pngBytes: Buffer
  /** Null when `buildPdf` was false. */
  pdfBytes: Buffer | null
  widthPx: number
  heightPx: number
}

/**
 * Pipeline: AI image bytes → resize:cover to exact print W×H → output PNG
 * → (optional) wrap PNG in a single-page PDF at the physical print size.
 *
 * `fit: 'cover'` will crop overflow when the source aspect ratio (e.g. 21:9
 * from Gemini) doesn't match the target (e.g. 4:1). The prompt instructs
 * Gemini to keep critical content in the central 80% of the canvas so the
 * crop doesn't eat headline/contact text — see `buildSpandukPrompt` in
 * `server/functions/spanduk.ts`.
 */
export async function composeSpanduk(
  params: ComposeSpandukParams,
): Promise<ComposeSpandukResult> {
  const { widthPx, heightPx } = pickOutputPixelSize(
    params.widthCm,
    params.heightCm,
  )

  const pngBytes = await sharp(params.imageBytes)
    .resize({ width: widthPx, height: heightPx, fit: 'cover', position: 'center' })
    .png({ compressionLevel: 8 })
    .toBuffer()

  let pdfBytes: Buffer | null = null
  if (params.buildPdf) {
    const ptPerCm = 28.3464567
    const pageWidth = params.widthCm * ptPerCm
    const pageHeight = params.heightCm * ptPerCm
    const pdfDoc = await PDFDocument.create()
    const pdfImage = await pdfDoc.embedPng(pngBytes)
    const page = pdfDoc.addPage([pageWidth, pageHeight])
    page.drawImage(pdfImage, {
      x: 0,
      y: 0,
      width: pageWidth,
      height: pageHeight,
    })
    pdfBytes = Buffer.from(await pdfDoc.save())
  }

  return { pngBytes, pdfBytes, widthPx, heightPx }
}
