/**
 * Server functions for the staff WhatsApp OTP login flow.
 *
 * Two endpoints, both PRE-SESSION (user is unauthenticated):
 *
 *   requestWaLoginOtp({ tenantSlug, phone })
 *     → { instancePhone, deepLink, tenantName, expectedReplyWithinSec }
 *
 *     Proxies POST /v1/auth/wa-login/request on the Go API. The browser
 *     opens `deepLink` (a wa.me URL with prefilled "Minta OTP Login
 *     Vintra" text) so the user can send the message that triggers
 *     OTP generation on the Go side. The OTP is NEVER generated by
 *     this endpoint — that only happens when the inbound WA message
 *     arrives at the tenant's instance (preserves the ban-safe
 *     "user-initiated conversation" property).
 *
 *   verifyWaLoginOtp({ tenantSlug, phone, otp })
 *     → { ok: true, accessToken, refreshToken }
 *
 *     Proxies POST /v1/auth/wa-login/verify. On success the API returns
 *     the staff identity (userId, optional synthetic authEmail, tenantId);
 *     we then mint a Supabase session via the admin generateLink +
 *     verifyOtp dance and hand the tokens back to the browser, which
 *     sets sb-access-token / sb-refresh-token cookies the same way the
 *     email/password login does. The synthetic-email branch is for
 *     phone-only staff invited without a real email; staff with a real
 *     email get its address resolved via admin.getUserById.
 *
 * Auth model: NEITHER server fn forwards the caller's Supabase cookies
 * to the API — the public /auth/wa-login/* endpoints are explicitly
 * unauthenticated, so attaching a stale cookie would just waste bytes.
 */
import { createServerFn } from '@tanstack/react-start'
import { createClient } from '@supabase/supabase-js'
import { db } from '@vintra/db'
import { tenants } from '@vintra/db/schema'
import { eq, or } from 'drizzle-orm'
import {
  waLoginRequestSchema,
  waLoginVerifySchema,
} from '@vintra/shared'

function apiUrl(path: string) {
  const base = process.env['API_URL'] ?? 'http://localhost:4000'
  return `${base}/v1${path}`
}

function getSupabaseServer() {
  return createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_SECRET_KEY!,
  )
}

// Public-endpoint fetch helper — deliberately does NOT forward cookies
// or Authorization headers. The Go side gates these routes as public;
// forwarding stale auth would just add noise to its access logs.
async function apiPublicFetch(path: string, body: unknown) {
  const res = await fetch(apiUrl(path), {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify(body),
  })
  const text = await res.text()
  let parsed: unknown
  try {
    parsed = text ? JSON.parse(text) : null
  } catch {
    parsed = { error: text }
  }
  if (!res.ok) {
    const err = (parsed as { error?: string } | null)?.error ?? res.statusText
    throw new ApiError(err, res.status)
  }
  return parsed
}

class ApiError extends Error {
  status: number
  constructor(message: string, status: number) {
    super(message)
    this.status = status
  }
}

/**
 * Resolve whatever the user typed in the URL to the canonical
 * `tenants.slug` the Go API expects. Accepts EITHER the auto-generated
 * slug or the owner-claimed `public_slug` vanity alias — staff get
 * `vintra.my.id/auth/wa-login/usama-steam` instead of
 * `…/syamsuddin-cahaya-mpbv7w5v`.
 *
 * Falls back to the raw input if no match (so the API still surfaces
 * its unified `wa_login_unavailable` error — we don't leak whether a
 * slug exists from this lookup).
 */
async function resolveCanonicalTenantSlug(input: string): Promise<string> {
  const [row] = await db
    .select({ slug: tenants.slug })
    .from(tenants)
    .where(or(eq(tenants.slug, input), eq(tenants.publicSlug, input)))
    .limit(1)
  return row?.slug ?? input
}

export const requestWaLoginOtp = createServerFn({ method: 'POST' })
  .inputValidator(waLoginRequestSchema)
  .handler(async ({ data }) => {
    const tenantSlug = await resolveCanonicalTenantSlug(data.tenantSlug)
    return (await apiPublicFetch('/auth/wa-login/request', {
      ...data,
      tenantSlug,
    })) as {
      instancePhone: string
      deepLink: string
      tenantName: string
      expectedReplyWithinSec: number
    }
  })

/**
 * Resolve the email to use for the Supabase magic-link mint. Two paths:
 *
 *   1. wa_login_email set on tenant_members (phone-only staff) →
 *      return it directly. No Supabase round-trip needed.
 *   2. NULL → staff has a real email. Look it up via admin.getUserById
 *      using the userId the API returned.
 *
 * Throws when the user can't be resolved (deleted between OTP request
 * and verify, etc.) — caller treats this as a 500.
 */
async function resolveAuthEmail(
  supabase: ReturnType<typeof getSupabaseServer>,
  userId: string,
  authEmail: string | undefined,
): Promise<string> {
  if (authEmail) return authEmail
  const { data, error } = await supabase.auth.admin.getUserById(userId)
  if (error || !data?.user?.email) {
    throw new Error(
      `wa-login: cannot resolve email for user ${userId}: ${error?.message ?? 'no email on user'}`,
    )
  }
  return data.user.email
}

export const verifyWaLoginOtp = createServerFn({ method: 'POST' })
  .inputValidator(waLoginVerifySchema)
  .handler(async ({ data }) => {
    // Step 1: API verifies the OTP + returns staff identity. If this
    // fails (wrong code, rate-limited, expired) we surface the API's
    // error message verbatim — the API already speaks our generic
    // error language ("otp_invalid", "rate_limited", etc.).
    const tenantSlug = await resolveCanonicalTenantSlug(data.tenantSlug)
    const apiResp = (await apiPublicFetch('/auth/wa-login/verify', {
      ...data,
      tenantSlug,
    })) as {
      userId: string
      authEmail?: string
      tenantId: string
    }

    const supabase = getSupabaseServer()
    const email = await resolveAuthEmail(
      supabase,
      apiResp.userId,
      apiResp.authEmail,
    )

    // Step 2: mint a magic link for that user. generateLink does not
    // send any email itself (despite the name) — it returns the
    // hashed_token we can immediately redeem for a session.
    const { data: linkData, error: linkError } =
      await supabase.auth.admin.generateLink({
        type: 'magiclink',
        email,
      })
    if (linkError || !linkData?.properties?.hashed_token) {
      throw new Error(
        `wa-login: generateLink failed: ${linkError?.message ?? 'no hashed_token'}`,
      )
    }

    // Step 3: redeem the hashed_token for an actual session. The
    // session is what the browser cookie code expects.
    const { data: session, error: verifyError } = await supabase.auth.verifyOtp({
      token_hash: linkData.properties.hashed_token,
      type: 'magiclink',
    })
    if (verifyError || !session?.session) {
      throw new Error(
        `wa-login: verifyOtp failed: ${verifyError?.message ?? 'no session'}`,
      )
    }

    // Hand the tokens back to the browser. The login page sets cookies
    // + tells the browser-side supabase client about the new session
    // (mirrors the email/password flow in routes/auth/login.tsx).
    return {
      ok: true as const,
      accessToken: session.session.access_token,
      refreshToken: session.session.refresh_token,
      expiresIn: session.session.expires_in,
      userId: apiResp.userId,
      tenantId: apiResp.tenantId,
    }
  })
